---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # clasp
  - package-ecosystem: "docker"
    directory: "/clasp"
    ignore:
      - dependency-name: "node"
        versions: ["19", "21", "23", "25"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/clasp"
    schedule:
      interval: "weekly"

  # github-backup
  - package-ecosystem: "docker"
    directory: "/github-backup"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/github-backup"
    schedule:
      interval: "weekly"

  # gitlab-backup
  - package-ecosystem: "docker"
    directory: "/gitlab-backup"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/gitlab-backup"
    schedule:
      interval: "weekly"

  # lesspass
  - package-ecosystem: "docker"
    directory: "/lesspass"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/lesspass"
    schedule:
      interval: "weekly"
