---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          # within Super Linter.
          fetch-depth: 0
      - name: Run GitHub Super Linter
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          # Parse only new or edited files for validation.
          VALIDATE_ALL_CODEBASE: false
          # Disable JSCPD due to github/super-linter#1400.
          VALIDATE_JSCPD: false
          # Set the linter configuration files.
          DOCKERFILE_HADOLINT_FILE_NAME: hadolint.yml
          MARKDOWN_CONFIG_FILE: markdownlint.yml
          # Set the default branch name.
          DEFAULT_BRANCH: master
          # Make Super Linter mark the status of each individual linter run in
          # the Checks section of a pull request. There is no need to set the
          # GitHub Secret as it is automatically set by GitHub, it only needs to
          # be passed to the action.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
