---
name: ubuntu-mirror

on:
  push:
    branches:
      - master
    paths:
      - ubuntu-mirror/**
  workflow_dispatch:

jobs:
  docker:
    name: Docker Image CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_args: |
              BASE_IMAGE_TAG=xenial
            platforms: |
              linux/386
              linux/amd64
              linux/arm
              linux/arm64
          - build_args: |
              BASE_IMAGE_TAG=bionic
            platforms: |
              linux/386
              linux/amd64
              linux/arm
              linux/arm64
          - build_args: |
              BASE_IMAGE_TAG=focal
            platforms: |
              linux/amd64
              linux/arm
              linux/arm64
          - build_args: |
              BASE_IMAGE_TAG=jammy
            platforms: |
              linux/amd64
              linux/arm
              linux/arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: ubuntu-mirror
          build-args: ${{ matrix.build_args }}
          platforms: ${{ matrix.platforms }}
